version: "3.9"
services:
  nginx:
    build:
      dockerfile: nginx/Dockerfile.nossl # change "nossl" to "ssl" for SSL support
    ports:
      - "80:80"
      # - "443:443" # uncomment for SSL support
    restart: unless-stopped
  server:
    build: server
    restart: unless-stopped